## import libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## Import the dataset

In [2]:
data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
data

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Create feature and label data

In [5]:
label =data['label']

In [6]:
dataset = data.iloc[:,1:]

In [7]:
dataset

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
len(label)

42000

In [9]:
label[0]

1

### Convert label data to one hot encoding

In [10]:
from keras.utils import to_categorical

In [11]:
label = to_categorical(label)

In [12]:
label[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

### Split the data into training and testing

In [13]:
# Taking 40000 images to Train the model
X_train = dataset[2000:]
y_train = label[2000:]

X_train.shape, y_train.shape

((40000, 784), (40000, 10))

In [14]:
X_test = dataset[:2000]
y_test = label[:2000]

X_test.shape, y_test.shape

((2000, 784), (2000, 10))

## Train the model

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [16]:
optimizer = Adam(lr=0.0001)

In [17]:
model = Sequential()

model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.compile(optimizer=optimizer
             ,loss='categorical_crossentropy'
             ,metrics=['accuracy'] )

In [18]:
model.fit(X_train,y_train,epochs=20)

Epoch 1/20
1250/1250 [==============================] - 7s 5ms/step - loss: 12.5988 - accuracy: 0.6621
Epoch 2/20
1250/1250 [==============================] - 6s 5ms/step - loss: 1.3385 - accuracy: 0.9034
Epoch 3/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.7061 - accuracy: 0.9333
Epoch 4/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.4242 - accuracy: 0.9501
Epoch 5/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.2895 - accuracy: 0.9628
Epoch 6/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.2020 - accuracy: 0.9681
Epoch 7/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.1346 - accuracy: 0.9769
Epoch 8/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.1104 - accuracy: 0.9788
Epoch 9/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0755 - accuracy: 0.9856
Epoch 10/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.0662 - accuracy: 0.9865
Epoch 11/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.0649 - accuracy: 0.9875
Epoch 12/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0512 - accuracy: 0.9901
Epoch 13/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0530 - accuracy: 0.9894
Epoch 14/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0500 - accuracy: 0.9892
Epoch 15/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0461 - accuracy: 0.9906
Epoch 16/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0326 - accuracy: 0.9932
Epoch 17/20
1250/1250 [==============================] - 6s 5ms/step - loss: 0.0361 - accuracy: 0.9932
Epoch 18/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.0450 - accuracy: 0.9915
Epoch 19/20
1250/1250 [==============================] - 7s 6ms/step - loss: 0.0281 - accuracy: 0.9934
Epoch 20/20
1250/1250 [==============================] - 7s 5ms/step - loss: 0.0326 - accuracy: 0.9937

In [19]:
model.evaluate(X_test,y_test)

63/63 [==============================] - 1s 3ms/step - loss: 0.7145 - accuracy: 0.9575

[0.7145341038703918, 0.9574999809265137]

In [20]:
test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
# Making Predictions on existing model.
prediction = model.predict(test)

# Rounding the prediction and converting float64 output to int64 output.
prediction = np.array(np.round(prediction), dtype='int64')

# Converting one-hot encoding into label encoding
prediction = (np.argmax(prediction, axis=1)).reshape(-1, 1)

# Creating a DataFrame similar to Example Submission
out = [{'ImageId': i+1, 'Label': prediction[i][0]} for i in range(len(prediction))]

# Creating a .csv file from the DataFrame
# pd.DataFrame(out).to_csv('./submission3.csv', index=False)

In [22]:
sub = pd.read_csv('sample_submission.csv')

In [23]:
sub.head()

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [24]:
sub.info

<bound method DataFrame.info of        ImageId  Label
0            1      0
1            2      0
2            3      0
3            4      0
4            5      0
...        ...    ...
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

[28000 rows x 2 columns]>

# img

In [25]:
imgdata = np.reshape(np.array(dataset),(dataset.shape[0],28,28,1))
imglabels = label

imgdata.shape, imglabels.shape

((42000, 28, 28, 1), (42000, 10))

In [26]:
img_train_data = imgdata[2000:]
img_train_labels = imglabels[2000:]

img_train_data.shape, img_train_labels.shape

((40000, 28, 28, 1), (40000, 10))

In [27]:
img_test_data = imgdata[:2000]
img_test_labels = imglabels[:2000]

img_test_data.shape, img_test_labels.shape

((2000, 28, 28, 1), (2000, 10))

In [28]:
plt.figure(figsize=(6, 6))
for i in range(25):
    plt.subplot(5, 5, i + 1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(img_train_data[i])
    plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined